# Setting for Semaphore CI
# Copy these configurations to the settings on Semaphore CI

project_settings:
  env_variables:
    DANGER_GITHUB_API_TOKEN: 'TOKEN'

  build_settings:
    setup:
      - export BRANCH_TAG=${BRANCH_NAME/\//-}

    unit_tests:
      - bundle exec danger
      - bundle exec rspec
