version: '3.2'

services:
  db:
    image: postgres:12.1
    container_name: danger_implementation_db
    environment:
      - POSTGRES_DB=danger_implementation_development
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.7
    container_name: danger_implementation_redis
    ports:
      - "6379:6379"
